export const SUPPORTED_LANGUAGES = [
  { code: 'EN', name: 'English' },
  { code: 'TA', name: 'தமிழ்' },
  { code: 'ML', name: 'മലയാളം' },
  { code: 'TE', name: 'తెలుగు' },
  { code: 'HI', name: 'हिन्दी' },
  { code: 'KN', name: 'ಕನ್ನಡ' }
];

// Type definition for our translation keys so TypeScript helps auto-complete
export type TranslationKeys = 
  | "bookings" | "help" | "planMyTour" | "from" | "to" | "dateOfJourney" 
  | "today" | "tomorrow" | "search" | "eazzyFilter" | "filterBuses" 
  | "sortBy" | "ratings" | "departureTime" | "price" | "viewSeats" 
  | "busesFound" | "searching" | "noBusesFound" | "onwards";

// The Translation Dictionary
export const TRANSLATIONS: Record<string, Record<TranslationKeys, string>> = {
  EN: {
    bookings: "Bookings",
    help: "Help",
    planMyTour: "Plan My Tour",
    from: "From",
    to: "To",
    dateOfJourney: "Date of journey",
    today: "Today",
    tomorrow: "Tomorrow",
    search: "SEARCH",
    eazzyFilter: "Eazzy filter",
    filterBuses: "Filter buses",
    sortBy: "Sort by:",
    ratings: "Ratings",
    departureTime: "Departure time",
    price: "Price",
    viewSeats: "View seats",
    busesFound: "buses found",
    searching: "Searching...",
    noBusesFound: "No buses found matching the selected filter.",
    onwards: "Onwards"
  },
  TA: {
    bookings: "முன்பதிவுகள்",
    help: "உதவி",
    planMyTour: "பயணத்தை திட்டமிடு",
    from: "புறப்படும் இடம்",
    to: "செல்லும் இடம்",
    dateOfJourney: "பயண தேதி",
    today: "இன்று",
    tomorrow: "நாளை",
    search: "தேடு",
    eazzyFilter: "எளிய வடிகட்டி",
    filterBuses: "பேருந்துகளை வடிகட்டு",
    sortBy: "வரிசைப்படுத்து:",
    ratings: "மதிப்பீடுகள்",
    departureTime: "புறப்படும் நேரம்",
    price: "விலை",
    viewSeats: "இருக்கைகளை காண்",
    busesFound: "பேருந்துகள் உள்ளன",
    searching: "தேடப்படுகிறது...",
    noBusesFound: "பொருத்தமான பேருந்துகள் இல்லை.",
    onwards: "முதல்"
  },
  HI: {
    bookings: "बुकिंग",
    help: "सहायता",
    planMyTour: "मेरा टूर प्लान करें",
    from: "कहाँ से",
    to: "कहाँ तक",
    dateOfJourney: "यात्रा की तिथि",
    today: "आज",
    tomorrow: "कल",
    search: "खोजें",
    eazzyFilter: "आसान फ़िल्टर",
    filterBuses: "बसें फ़िल्टर करें",
    sortBy: "क्रमबद्ध करें:",
    ratings: "रेटिंग",
    departureTime: "प्रस्थान का समय",
    price: "किराया",
    viewSeats: "सीटें देखें",
    busesFound: "बसें मिलीं",
    searching: "खोजा जा रहा है...",
    noBusesFound: "कोई बस नहीं मिली.",
    onwards: "से शुरू"
  },
  TE: {
    bookings: "బుకింగ్స్",
    help: "సహాయం",
    planMyTour: "టూర్ ప్లాన్ చేయండి",
    from: "నుండి",
    to: "గమ్యస్థానం",
    dateOfJourney: "ప్రయాణ తేదీ",
    today: "ఈ రోజు",
    tomorrow: "రేపు",
    search: "శోధించండి",
    eazzyFilter: "సులభమైన ఫిల్టర్",
    filterBuses: "బస్సులను ఫిల్టర్ చేయండి",
    sortBy: "క్రమబద్ధీకరించు:",
    ratings: "రేటింగ్‌లు",
    departureTime: "బయలుదేరు సమయం",
    price: "ధర",
    viewSeats: "సీట్లను చూడండి",
    busesFound: "బస్సులు కనుగొనబడ్డాయి",
    searching: "వెతుకుతోంది...",
    noBusesFound: "బస్సులు దొరకలేదు.",
    onwards: "నుండి"
  },
  ML: {
    bookings: "ബുക്കിംഗുകൾ",
    help: "സഹായം",
    planMyTour: "യാത്ര പ്ലാൻ ചെയ്യുക",
    from: "എവിടെ നിന്ന്",
    to: "എവിടേക്ക്",
    dateOfJourney: "യാത്രാ തീയതി",
    today: "ഇന്ന്",
    tomorrow: "നാളെ",
    search: "തിരയുക",
    eazzyFilter: "എളുപ്പമുള്ള ഫിൽട്ടർ",
    filterBuses: "ബസുകൾ ഫിൽട്ടർ ചെയ്യുക",
    sortBy: "ക്രമീകരിക്കുക:",
    ratings: "റേറ്റിംഗുകൾ",
    departureTime: "പുറപ്പെടുന്ന സമയം",
    price: "വില",
    viewSeats: "സീറ്റുകൾ കാണുക",
    busesFound: "ബസുകൾ കണ്ടെത്തി",
    searching: "തിരയുന്നു...",
    noBusesFound: "ബസുകൾ കണ്ടെത്താനായില്ല.",
    onwards: "മുതൽ"
  },
  KN: {
    bookings: "ಬುಕಿಂಗ್‌ಗಳು",
    help: "ಸಹಾಯ",
    planMyTour: "ಪ್ರವಾಸವನ್ನು ಯೋಜಿಸಿ",
    from: "ಇಲ್ಲಿಂದ",
    to: "ಇಲ್ಲಿಗೆ",
    dateOfJourney: "ಪ್ರಯಾಣದ ದಿನಾಂಕ",
    today: "ಇಂದು",
    tomorrow: "ನಾಳೆ",
    search: "ಹುಡುಕಿ",
    eazzyFilter: "ಸುಲಭ ಫಿಲ್ಟರ್",
    filterBuses: "ಬಸ್‌ಗಳನ್ನು ಫಿಲ್ಟರ್ ಮಾಡಿ",
    sortBy: "ವಿಂಗಡಿಸಿ:",
    ratings: "ರೇಟಿಂಗ್‌ಗಳು",
    departureTime: "ಹೊರಡುವ ಸಮಯ",
    price: "ಬೆಲೆ",
    viewSeats: "ಸೀಟುಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    busesFound: "ಬಸ್‌ಗಳು ಕಂಡುಬಂದಿವೆ",
    searching: "ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    noBusesFound: "ಯಾವುದೇ ಬಸ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    onwards: "ನಂತರ"
  }
}; 